WebApplication/Pages/Account/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

using MeetMe.Core.Interfaces;
using MeetMe.Core.Models;

namespace MeetMe.Web.Pages.Account
{
    public class ChangePasswordForm
    {
        [Required(ErrorMessage = "Password is required")]
        public string Password { get; set; }
        [Required(ErrorMessage = "Password Confirmation is required")]
        [Compare("Password", ErrorMessage = "Password Confirmation is required")]
        public string ConfirmPassword { get; set; }
    }

    public class EditModel : PageModel
    {
        private readonly IUserService _userService;
        private readonly IUserContextService _userContextService;

        private const string USER_ID_QS_KEY = "userId";

        [BindProperty]
        public User EditedUser { get; set; }
        [BindProperty]
        public ChangePasswordForm ChangePassword { get; set; }
        [BindProperty]
        public int EditedUserId { get; set; }

        public bool ShowApprovedStatus { get; set; }
        public string ApprovedStatus { get; set; }
        public bool IsAdmin { get; set; }

        public EditModel(IUserService userService, IUserContextService userContextService)
        {
            this._userService = userService;
            this._userContextService = userContextService;            
        }

        private User GetUserToEdit()
        {
            User currentUser = this._userContextService.GetLoggedInUser();
            User userToEdit;
            IsAdmin = currentUser.Role == Core.Models.User.RoleType.Admin;
            bool requestHasUserId = HttpContext.Request.Query.ContainsKey(USER_ID_QS_KEY);

            if (IsAdmin && requestHasUserId)
            {
                int editedUserId = int.Parse(HttpContext.Request.Query[USER_ID_QS_KEY]);
                userToEdit = _userService.GetUserById(editedUserId);
            } else
            {
                userToEdit = currentUser;
            }

            ShowApprovedStatus = currentUser.Role == Core.Models.User.RoleType.ServiceProvider;
            ApprovedStatus = userToEdit.IsApproved ? "Approved" : "Not Approved";
            return userToEdit;
        }

        private void FilterPasswordFieldErrors(bool keepPasswordFields)
        {
            foreach (var field in ModelState)
            {
                if (field.Value.ValidationState == Microsoft.AspNetCore.Mvc.ModelBinding.ModelValidationState.Invalid)
                {
                    bool isPasswordField = field.Key.Contains("Password") || field.Key.Contains("ConfirmPassword");
                    bool shouldClearErrors = (isPasswordField && !keepPasswordFields) || (!isPasswordField && keepPasswordFields);
                    if (shouldClearErrors)
                    {
                        field.Value.ValidationState = Microsoft.AspNetCore.Mvc.ModelBinding.ModelValidationState.Valid;
                    }
                }
            }
        }

        public void OnGet()
        {
            EditedUser = GetUserToEdit();
            EditedUserId = EditedUser.UserId;
        }

        public IActionResult OnPostUpdateUserAsync()
        {
            FilterPasswordFieldErrors(false);
            if (!ModelState.IsValid) return Page();            
            EditedUser.UserId = EditedUserId;
            _userService.UpdateUser(EditedUser);
            return RedirectToPage(_userContextService.GetRoutingStrategy().GetHomeRoute());
        }

        public IActionResult OnPostChangePasswordAsync()
        {
            FilterPasswordFieldErrors(true);
            if (!ModelState.IsValid) return Page();            
            _userService.UpdatePassword(EditedUserId, ChangePassword.Password);
            return RedirectToPage(_userContextService.GetRoutingStrategy().GetHomeRoute());
        }

    }
}

WebApplication/Pages/Account/Login.cshtml.cs
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Localization;

using MeetMe.Core.Interfaces;
using MeetMe.Core.Models;
using MeetMe.Web.Resources;

namespace MeetMe.Web.Pages.Account
{
    public class LoginData
    {
        [Required(ErrorMessage="Email is required")]
        public string Email { get; set; }

        [Required(ErrorMessage="Password is required"), DataType(DataType.Password)]
        public string Password { get; set; }

        public bool RememberMe { get; set; }
    }

    public class LoginModel : PageModel
    {
        private readonly IUserService _userService;
        private readonly IUserContextService _userContextService;
        private readonly IStringLocalizer<ValidationResources> _stringLocalizer;

        [BindProperty]
        public LoginData LoginData { get; set; }

        public LoginModel(IUserService userService, 
                          IUserContextService userContextService,
                          IStringLocalizer<ValidationResources> stringLocalizer)
        {
            _userService = userService;
            _userContextService = userContextService;
            _stringLocalizer = stringLocalizer;            
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid) {
                return Page();
            }

            try {
                User loggedInUser = this._userService.VerifyPasswordAndGetUser(LoginData.Email, LoginData.Password);
                await _userContextService.LoginAsync(loggedInUser, LoginData.RememberMe);
                return RedirectToPage(Utilities.Routes.Home);
            }
            catch (AccountNotActiveException) {
                return FormError("Email", "Account Not Active");
            }
            catch (EntityNotFoundException) {
                return FormError("Email", "Email not found");
            }
            catch (WrongPasswordException) {
                return FormError("Password", "Wrong password");
            }
        }   

        private IActionResult FormError(string field, string message)
        {
            ModelState.AddModelError(field, _stringLocalizer.GetString(message));
            return Page();
        }
    }
}

WebApplication/Pages/Account/Logout.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Authentication;
using Microsoft.Extensions.Logging;
using MeetMe.Core.Interfaces;

namespace MeetMe.Web.Pages.Account
{
    public class LogoutModel : PageModel
    {
        private readonly ILoginService _loginService;

        public LogoutModel(ILoginService loginService)
        {
            _loginService = loginService;
        }

        public async Task<IActionResult> OnGetAsync()
        {
            await _loginService.LogoutAsync();
            return RedirectToPage(Utilities.Routes.Login);
        }
    }
}

WebApplication/Pages/Account/Register.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

using MeetMe.Core.Interfaces;
using MeetMe.Core.Models;
using Microsoft.Extensions.Localization;
using MeetMe.Web.Resources;

namespace MeetMe.Web.Pages.Account
{
    public class RegisterModel : PageModel
    {
        private readonly IUserService _userService;
        private readonly IUserContextService _userContextService;
        private readonly IStringLocalizer<ValidationResources> _stringLocalizer;

        public RegisterModel(IUserService userService, 
                             IUserContextService userContextService,
                             IStringLocalizer<ValidationResources> stringLocalizer)
        {
            _userService = userService;
            _userContextService = userContextService;
            _stringLocalizer = stringLocalizer;
        }

        [BindProperty]
        public RegisterRequest RegisterForm { get; set; }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid) return Page();

            try {
                var newUser = _userService.CreateUser(RegisterForm);
                await _userContextService.LoginAsync(newUser, true);
                return RedirectToPage(Utilities.Routes.Home);
            } 
            catch(EntityAlreadyExistsException) {
                return FormError("Email", "Account already exists");
            }
            catch(PasswordConfirmMismatchException) {
                return FormError("ConfirmPassword", "Passwords do not match");
            }
        }

        public IActionResult FormError(string field, string message)
        {
            ModelState.AddModelError(field, _stringLocalizer.GetString(message));
            return Page();
        }
    }
}

WebApplication/Pages/Account/Edit.cshtml
@page
@model MeetMe.Web.Pages.Account.EditModel
@{ ViewData["Title"] = RS["Edit Account"]; }

<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <form method="post" class="form-horizontal">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label>@RS["Email"] </label>
                <input asp-for="EditedUser.Email" class="form-control" />
            </div>
            <div class="form-group">
                @if (Model.EditedUser.Role == Core.Models.User.RoleType.ServiceProvider)
                {
                    <label>@RS["Business Name"]</label>
                }
                else
                {
                    <label>@RS["Name"]</label>
                }
                <input asp-for="EditedUser.Name" class="form-control" />
            </div>
            <div class="form-group">
                @if (Model.EditedUser.Role == Core.Models.User.RoleType.ServiceProvider)
                {
                    <label>@RS["Business Phone"]</label>
                }
                else
                {                    
                    <label>@RS["Phone"]</label>
                }
                <input asp-for="EditedUser.Phone" class="form-control" />
            </div>

            @if (Model.ShowApprovedStatus)
            {
                <div class="form-group">
                    <label>@RS["Account Status"]</label>
                    <p>
                        <span class="badge">@RS[Model.ApprovedStatus]</span>
                    </p>
                </div>
            }

            @if (Model.IsAdmin)
            {
                <div class="form-group">
                    <div class="checkbox">
                        <label>
                            <input asp-for="EditedUser.IsApproved" type="checkbox">
                            @RS["Approved"]
                        </label>
                    </div>
                </div>
                <div class="form-group">
                    <div class="checkbox">
                        <label>
                            <input asp-for="EditedUser.IsActive" type="checkbox">
                            @RS["Active"]
                        </label>
                    </div>
                </div>
            }

            <input type="hidden" asp-for="EditedUserId" />
            <input type="submit" class="btn btn-primary pull-right" value="@RS["Save Changes"]" asp-page-handler="UpdateUser"  />
            @Html.AntiForgeryToken()
        </form>
    </div>
</div>

<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <form method="post" class="form-horizontal">
            <h4>@RS["Change Password"]</h4>
            <div class="form-group">
                <label>@RS["Password"] </label>
                <input asp-for="ChangePassword.Password" class="form-control" type="password" />
            </div>
            <div class="form-group">
                <label>@RS["Confirm Password"]</label>
                <input asp-for="ChangePassword.ConfirmPassword" class="form-control" type="password" />
            </div>

            <input type="hidden" asp-for="EditedUserId" />
            <input type="submit" class="btn btn-warning pull-right" value="@RS["Change Password"]" asp-page-handler="ChangePassword" />
            @Html.AntiForgeryToken()
        </form>
    </div>
</div>

WebApplication/Pages/Account/Login.cshtml
@page
@model MeetMe.Web.Pages.Account.LoginModel
@{ ViewData["Title"] = RS["Login"]; }
<div class="row">
    <div class="col-md-8 col-md-offset-2">

        <form method="post" class="form">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label>@RS["Email"]</label>
                <input asp-for="LoginData.Email" class="form-control" type="email" />
            </div>
            <div class="form-group">
                <label>@RS["Password"]</label>
                <input asp-for="LoginData.Password" class="form-control" />
            </div>
            <div class="checkbox">
                <label>
                    <input asp-for="LoginData.RememberMe" type="checkbox" />
                    @RS["Remember me"]
                </label>
            </div>
            <input class="btn btn-primary" type="submit" value="@RS["Login"]" />
            <a class="help-block" asp-page="@Routes.Register">@RS["Register"]</a>
            @Html.AntiForgeryToken()
        </form>
    </div>
</div>

WebApplication/Pages/Account/Logout.cshtml
@page
@model MeetMe.Web.Pages.Account.LogoutModel
@{
    Layout = null;
}

WebApplication/Pages/Account/Register.cshtml
@page
@model MeetMe.Web.Pages.Account.RegisterModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{ ViewData["Title"] = RS["Register"]; }
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <form method="POST">
            <div asp-validation-summary="All" class="text-danger"></div>
            <br />
            <div class="form-group">
                <label>@RS["Email"]</label>
                <input class="form-control" type="email" asp-for="RegisterForm.Email" />
            </div>
            <div class="form-group">
                <label>@RS["Password"]</label>
                <input class="form-control" type="password" asp-for="RegisterForm.Password" />
            </div>
            <div class="form-group">
                <label>@RS["Confirm Password"]</label>
                <input class="form-control" type="password" asp-for="RegisterForm.ConfirmPassword" />
            </div>
            <div class="checkbox">
                <label>
                    <input id="isServiceProviderCheckBox" asp-for="RegisterForm.IsServiceProvider" />
                    @RS["Service Provider"]
                </label>
            </div>
            <div class="form-group">
                <label id="nameLabel">@RS["Name"]</label>
                <input class="form-control" asp-for="RegisterForm.Name" />
            </div>
            <div class="form-group">
                <label id="phoneLabel">@RS["Phone"]</label>
                <input class="form-control" asp-for="RegisterForm.Phone" />
            </div>
            <input class="btn btn-primary" type="submit" value="@RS["Register"]" />
            <a class="help-block" asp-page="@Routes.Login">@RS["Login"]</a>
        </form>
    </div>
</div>

@section Scripts {
<script type="text/javascript">
    function decodeText(s) { // needed for unicode
        u = s.split(';').map(l => l.replace('&#x', '\\u0')).join('');
        return JSON.parse('"' + u + '"');
    }

    function updateInputText(inputSelector, text) {
        $(inputSelector).text(decodeText(text));
    }

    document.addEventListener('DOMContentLoaded', function () {
        $(document).ready(function () {
            $('#isServiceProviderCheckBox').change(function (e) {
                if (e.target.checked) {
                    updateInputText('#nameLabel', '@RS["Business Name"]');
                    updateInputText('#phoneLabel', '@RS["Business Phone"]');
                } else {
                    updateInputText('#nameLabel', '@RS["Name"]');
                    updateInputText('#phoneLabel', '@RS["Phone"]');
                }
            });
        });
    });
</script>
}